In [ ]:
#Tensors


In [ ]:
import torch

In [ ]:
data = [[1,2], [3,4], [5,6]]
data

[[1, 2], [3, 4], [5, 6]]

In [ ]:
torch.tensor(data)

tensor([[1, 2],
        [3, 4],
        [5, 6]])

In [ ]:
#making a list by numpy

In [ ]:
import numpy as np
np_array = np.array(data)
np_array

array([[1, 2],
       [3, 4],
       [5, 6]])

In [ ]:
torch.from_numpy(np_array)

tensor([[1, 2],
        [3, 4],
        [5, 6]])

In [ ]:
x = torch.zeros(3,3,5, dtype=torch.float16)
print(x, x.dtype)

tensor([[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]], dtype=torch.float16) torch.float16


In [ ]:
x = torch.ones(3,3,5)
print(x, x.dtype)

tensor([[[1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.]],

        [[1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.]],

        [[1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.]]]) torch.float32


In [ ]:
x = torch.rand(3,3,5)
print(x, x.dtype)

tensor([[[0.7453, 0.5350, 0.5328, 0.6365, 0.1540],
         [0.9668, 0.4254, 0.4870, 0.4294, 0.0730],
         [0.2120, 0.1323, 0.8468, 0.7136, 0.9508]],

        [[0.0494, 0.5502, 0.7054, 0.4321, 0.9691],
         [0.6791, 0.9651, 0.5399, 0.4909, 0.2394],
         [0.4560, 0.7258, 0.3962, 0.2877, 0.9949]],

        [[0.5269, 0.3867, 0.9212, 0.9257, 0.3437],
         [0.6397, 0.2855, 0.0860, 0.0643, 0.0848],
         [0.8712, 0.0485, 0.8262, 0.3261, 0.0680]]]) torch.float32


In [ ]:
x[0]

tensor([[0.7453, 0.5350, 0.5328, 0.6365, 0.1540],
        [0.9668, 0.4254, 0.4870, 0.4294, 0.0730],
        [0.2120, 0.1323, 0.8468, 0.7136, 0.9508]])

In [ ]:
x = torch.tensor([1,2,3,4,5])
print(x, x.dtype)

tensor([1, 2, 3, 4, 5]) torch.int64


In [ ]:
y = (2*x)
print(y, y.dtype)

tensor([ 2,  4,  6,  8, 10]) torch.int64
