<a href="https://colab.research.google.com/github/ebiram63/Pytorch_course/blob/main/part3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
#Tensors


In [ ]:
import torch

In [ ]:
data = [[1,2], [3,4], [5,6]]
data

[[1, 2], [3, 4], [5, 6]]

In [ ]:
torch.tensor(data)

NameError: name 'data' is not defined

In [ ]:
#making a list by numpy

In [ ]:
import numpy as np
np_array = np.array(data)
np_array

array([[1, 2],
       [3, 4],
       [5, 6]])

In [ ]:
torch.from_numpy(np_array)

tensor([[1, 2],
        [3, 4],
        [5, 6]])

In [ ]:
x = torch.zeros(3,3,5, dtype=torch.float16)
print(x, x.dtype)

tensor([[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]], dtype=torch.float16) torch.float16


In [ ]:
x = torch.ones(3,3,5)
print(x, x.dtype)

tensor([[[1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.]],

        [[1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.]],

        [[1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.]]]) torch.float32


In [ ]:
x = torch.rand(3,3,5)
print(x, x.dtype)

tensor([[[0.7453, 0.5350, 0.5328, 0.6365, 0.1540],
         [0.9668, 0.4254, 0.4870, 0.4294, 0.0730],
         [0.2120, 0.1323, 0.8468, 0.7136, 0.9508]],

        [[0.0494, 0.5502, 0.7054, 0.4321, 0.9691],
         [0.6791, 0.9651, 0.5399, 0.4909, 0.2394],
         [0.4560, 0.7258, 0.3962, 0.2877, 0.9949]],

        [[0.5269, 0.3867, 0.9212, 0.9257, 0.3437],
         [0.6397, 0.2855, 0.0860, 0.0643, 0.0848],
         [0.8712, 0.0485, 0.8262, 0.3261, 0.0680]]]) torch.float32


In [ ]:
x[0]

tensor([[0.7453, 0.5350, 0.5328, 0.6365, 0.1540],
        [0.9668, 0.4254, 0.4870, 0.4294, 0.0730],
        [0.2120, 0.1323, 0.8468, 0.7136, 0.9508]])

In [ ]:
x = torch.tensor([1,2,3,4,5])
print(x, x.dtype)

tensor([1, 2, 3, 4, 5]) torch.int64


In [ ]:
y = (2*x)
print(y, y.dtype)

tensor([ 2,  4,  6,  8, 10]) torch.int64


In [ ]:
((0.0 * x) - y)

tensor([ -2.,  -4.,  -6.,  -8., -10.])

In [ ]:
((0.0 * x) - y ).dtype

torch.float32

In [ ]:
tensor = torch.tensor(data)
print(tensor)
print("-"*30)
print(f"Shape  : {tensor.shape}")
print(f"Datatype : {tensor.dtype}" )
print(f"Device :  {tensor.device}")

tensor([[1, 2],
        [3, 4],
        [5, 6]])
------------------------------
Shape  : torch.Size([3, 2])
Datatype : torch.int64
Device :  cpu


In [ ]:
# We move our tensor to the GPU if available
if torch.cuda.is_available():
  tensor = tensor.to("cuda")

In [ ]:
print(tensor.device)

cpu


In [ ]:
#1- Indexing & Slicing:

In [ ]:
tensor = torch.rand(4,4)
print(tensor)


tensor([[0.7918, 0.3580, 0.4862, 0.8096],
        [0.0094, 0.9975, 0.1444, 0.3850],
        [0.0077, 0.1187, 0.8902, 0.6507],
        [0.0292, 0.8185, 0.1220, 0.2827]])


In [ ]:
print(f"First row : {tensor[0]}" )

First row : tensor([0.0849, 0.3500, 0.4536, 0.6255])


In [ ]:
print(f"First column: {tensor[ : , 0]}")

First column: tensor([0.0849, 0.5608, 0.6948, 0.9260])


In [ ]:
print(f"Last column: {tensor[..., -1]}")

Last column: tensor([0.6255, 0.4824, 0.3657, 0.2290])


In [ ]:
tensor[:,0] = 0
print(tensor)

tensor([[0.0000, 0.3580, 0.4862, 0.8096],
        [0.0000, 0.9975, 0.1444, 0.3850],
        [0.0000, 0.1187, 0.8902, 0.6507],
        [0.0000, 0.8185, 0.1220, 0.2827]])


In [ ]:
#2- Joining tensors
#torch.cat torch.stack


In [ ]:
tensor = torch.tensor([[1,2],[2,2],[3,3]])
print(tensor,tensor.shape)

tensor([[1, 2],
        [2, 2],
        [3, 3]]) torch.Size([3, 2])


In [ ]:
t1 = torch.cat([tensor,tensor,tensor], dim=1)
print(t1,t1.shape)

tensor([[1, 2, 1, 2, 1, 2],
        [2, 2, 2, 2, 2, 2],
        [3, 3, 3, 3, 3, 3]]) torch.Size([3, 6])


In [ ]:
t1 = torch.cat([tensor,tensor,tensor] , dim=0)
print(t1,t1.shape)

tensor([[1, 2],
        [2, 2],
        [3, 3],
        [1, 2],
        [2, 2],
        [3, 3],
        [1, 2],
        [2, 2],
        [3, 3]]) torch.Size([9, 2])


In [ ]:
t1 = torch.stack([tensor,tensor,tensor])
print(t1,t1.shape)

tensor([[[1, 2],
         [2, 2],
         [3, 3]],

        [[1, 2],
         [2, 2],
         [3, 3]],

        [[1, 2],
         [2, 2],
         [3, 3]]]) torch.Size([3, 3, 2])


In [ ]:
#3- Matrix Operations
#Transpose of a tensor -----> tensor.T
#matrix multiplication -----> tensor.matmul( tensor2 )
#matrix multiplication -----> tensor @ tensor2

In [ ]:
tensor = torch.Tensor([[1,1],[2,2],[3,3]])
tensor

tensor([[1., 1.],
        [2., 2.],
        [3., 3.]])

In [ ]:
tensor.T

tensor([[1., 2., 3.],
        [1., 2., 3.]])

In [ ]:
tensor.T @ tensor

tensor([[14., 14.],
        [14., 14.]])

In [ ]:
(tensor.T).matmul(tensor)

tensor([[14., 14.],
        [14., 14.]])

In [ ]:
tensor

tensor([[1., 1.],
        [2., 2.],
        [3., 3.]])

In [ ]:
tensor * tensor

tensor([[1., 1.],
        [4., 4.],
        [9., 9.]])

In [ ]:
x = tensor + tensor
x

tensor([[2., 2.],
        [4., 4.],
        [6., 6.]])

In [ ]:
print(tensor)
tensor.add_(5)
print('-'*20)
print(tensor)

tensor([[1., 1.],
        [2., 2.],
        [3., 3.]])
--------------------
tensor([[6., 6.],
        [7., 7.],
        [8., 8.]])


In [ ]:
w = torch.rand(5,4)
w

tensor([[0.7824, 0.6740, 0.1472, 0.6912],
        [0.0054, 0.7094, 0.5867, 0.3453],
        [0.1500, 0.9962, 0.3950, 0.0012],
        [0.7187, 0.6127, 0.5640, 0.6510],
        [0.9715, 0.7024, 0.4977, 0.6380]])

In [ ]:
w.view(4,5)


tensor([[0.7824, 0.6740, 0.1472, 0.6912, 0.0054],
        [0.7094, 0.5867, 0.3453, 0.1500, 0.9962],
        [0.3950, 0.0012, 0.7187, 0.6127, 0.5640],
        [0.6510, 0.9715, 0.7024, 0.4977, 0.6380]])

In [ ]:
w.view(10,2)

tensor([[0.7824, 0.6740],
        [0.1472, 0.6912],
        [0.0054, 0.7094],
        [0.5867, 0.3453],
        [0.1500, 0.9962],
        [0.3950, 0.0012],
        [0.7187, 0.6127],
        [0.5640, 0.6510],
        [0.9715, 0.7024],
        [0.4977, 0.6380]])