<a href="https://colab.research.google.com/github/ebiram63/Pytorch_course/blob/main/part4.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import torch

In [ ]:
#Gradient descent (نزول گرادیان)

In [2]:
torch.tensor([1, 2, 3, 4, 5], requires_grad=True)

RuntimeError: Only Tensors of floating point and complex dtype can require gradients

In [3]:
xg = torch.ones(5,2, requires_grad=True)
xg

tensor([[1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.]], requires_grad=True)

In [4]:
xg.requires_grad

True

In [5]:
layer1 = xg + 2
layer1

tensor([[3., 3.],
        [3., 3.],
        [3., 3.],
        [3., 3.],
        [3., 3.]], grad_fn=<AddBackward0>)

In [6]:
layer2 = xg * 2
layer2

tensor([[2., 2.],
        [2., 2.],
        [2., 2.],
        [2., 2.],
        [2., 2.]], grad_fn=<MulBackward0>)

In [7]:
layer3 = layer2.mean()
layer3

tensor(2., grad_fn=<MeanBackward0>)

In [8]:
layer2_detach = layer2.detach()
layer2_detach.detach()

tensor([[2., 2.],
        [2., 2.],
        [2., 2.],
        [2., 2.],
        [2., 2.]])

In [9]:
layer2_detach.mean()

tensor(2.)

In [ ]:
#Context-manager that disables gradient calculation

In [10]:
x = layer2 * 2
print(x)

tensor([[4., 4.],
        [4., 4.],
        [4., 4.],
        [4., 4.],
        [4., 4.]], grad_fn=<MulBackward0>)


In [11]:
print(x.requires_grad)

True


In [12]:
with torch.no_grad():
  x = layer2 * 2
  print(x)
  print(x.requires_grad)

tensor([[4., 4.],
        [4., 4.],
        [4., 4.],
        [4., 4.],
        [4., 4.]])
False


In [ ]:
#آموزش یک مدل ساده بدون گرادیان‌ پای تورچ

In [19]:
x = torch.tensor([1, 2, 3, 4], dtype=torch.float32)
Y = torch.tensor([2, 4, 6, 8], dtype=torch.float32)

def forward(x, w):
    return w * x

def loss(y, y_predicted):
    return ((y_predicted - y)**2).mean()

def gradient(x, y, y_predicted):
    return ((2.0 * x) * (y_predicted - y)).mean()

w = 0.0
n_iters = 30
learning_rate = 0.1

for epoch in range(n_iters):
    # Forward pass
    y_pred = forward(x, w)

    # Loss calculation
    l = loss(Y, y_pred)

    # Gradient calculation
    grad = gradient(x, Y, y_pred)

    print(f'Epoch: {epoch+1}, Predictions: {y_pred.detach()}, w: {w:.4f}, Grad: {grad.item():.5f}, Loss: {l:.5f}')

    # Weight update
    w -= learning_rate * grad

Epoch: 1, Predictions: tensor([0., 0., 0., 0.]), w: 0.0000, Grad: -30.00000, Loss: 30.00000
Epoch: 2, Predictions: tensor([ 3.,  6.,  9., 12.]), w: 3.0000, Grad: 15.00000, Loss: 7.50000
Epoch: 3, Predictions: tensor([1.5000, 3.0000, 4.5000, 6.0000]), w: 1.5000, Grad: -7.50000, Loss: 1.87500
Epoch: 4, Predictions: tensor([2.2500, 4.5000, 6.7500, 9.0000]), w: 2.2500, Grad: 3.75000, Loss: 0.46875
Epoch: 5, Predictions: tensor([1.8750, 3.7500, 5.6250, 7.5000]), w: 1.8750, Grad: -1.87500, Loss: 0.11719
Epoch: 6, Predictions: tensor([2.0625, 4.1250, 6.1875, 8.2500]), w: 2.0625, Grad: 0.93750, Loss: 0.02930
Epoch: 7, Predictions: tensor([1.9688, 3.9375, 5.9062, 7.8750]), w: 1.9688, Grad: -0.46875, Loss: 0.00732
Epoch: 8, Predictions: tensor([2.0156, 4.0312, 6.0469, 8.0625]), w: 2.0156, Grad: 0.23438, Loss: 0.00183
Epoch: 9, Predictions: tensor([1.9922, 3.9844, 5.9766, 7.9688]), w: 1.9922, Grad: -0.11719, Loss: 0.00046
Epoch: 10, Predictions: tensor([2.0039, 4.0078, 6.0117, 8.0156]), w: 2.0039